- name: Task Failure Exercise
  hosts: ansi-node1
  vars:
    web_package: http
    db_package: mariadb-server
    db_service: mariadb

  tasks:
    - name: Install {{ web_package }} package
      dnf:
        name: "{{ web_package }}"
        state: present

    - name: Install {{ db_package }} package
      dnf:
        name: "{{ db_package }}"
        state: present
